site_name: Docs.Level114
site_description: Documentation for Level 114 - the first gaming subnet on Bittensor, pioneering decentralized gaming infrastructure validation starting with Minecraft servers
site_url: https://docs.level114.io
repo_url: https://github.com/Level114/docs.git
repo_name: Level114

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: green
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
  font:
    text: Fira Code
    code: Fira Code
  logo: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjMDEwNDA5Ii8+Cjx0ZXh0IHg9IjEyIiB5PSIxNSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzAwZmYwMCIgZm9udC1mYW1pbHk9Im1vbm9zcGFjZSIgZm9udC1zaXplPSI4IiBmb250LXdlaWdodD0iYm9sZCI+MTE0PC90ZXh0Pgo8cmVjdCB4PSIyIiB5PSIyIiB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzAwZmYwMCIgc3Ryb2tlLXdpZHRoPSIxIi8+Cjwvc3ZnPgo=
  favicon: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjMyIiBoZWlnaHQ9IjMyIiBmaWxsPSIjMDEwNDA5Ii8+Cjx0ZXh0IHg9IjE2IiB5PSIyMCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzAwZmYwMCIgZm9udC1mYW1pbHk9Im1vbm9zcGFjZSIgZm9udC1zaXplPSIxMCIgZm9udC13ZWlnaHQ9ImJvbGQiPjExNDwvdGV4dD4KPHJlY3QgeD0iMiIgeT0iMiIgd2lkdGg9IjI4IiBoZWlnaHQ9IjI4IiBmaWxsPSJub25lIiBzdHJva2U9IiMwMGZmMDAiIHN0cm9rZS13aWR0aD0iMSIvPgo8L3N2Zz4K

nav:
  - What is Level114?: index.md
  - Getting Started:
      - Miner Setup: getting-started/setup-miner.md
      - Validator Setup: getting-started/setup-validator.md
  - Architecture:
      - System Overview: architecture/overview.md
  - Plugins:
      - Overview: plugins/overview.md
      - Minecraft Plugin: plugins/minecraft.md
  - Tokenomics:
      - Rewards & Distribution: tokenomics/rewards.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.mark
  - attr_list

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/level114
      name: Level 114 on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.level114.io
      name: Join our Discord
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/level_114
      name: Follow us on X
